project:
  type: book

book:
  title: "NYC Open Data"
  author: "Stat 3702 Spring 2026"
  date: today
  repo-url: https://github.com/jtr13/3702project
  repo-branch: main
  repo-actions: [source, edit, issue]
  chapters:
    - index.qmd
    - affordablehousing.qmd
    - nyc_shelter_census.qmd
    - instructions.qmd
    
  
format:
  html:
    theme: [default, styles/edav3.scss]
    highlight-style: styles/joyce.theme
    callout-icon: false
    
knitr:
  opts_chunk: 
    fig.align: center
    
execute:
  echo: true
  warning: false
  message: false

editor: source




